config/routes.rb
Rails.application.routes.draw do
  
  resources :articles do
    resources :comments
  end

  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy

  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # http_basic_authenticate_with email: "jeff.millar@sbcglobal.net", password: "665544", except: [:index, :show]


  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
 
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])
 
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end


  private

    def article_params
      params.require(:article).permit(:title, :text)    
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # http_basic_authenticate_with email: "jeff.millar@sbcglobal.net", password: "665544", only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @articles = Article.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<form>
  <%= form_for @article do |f| %>
    
    <div class="form-group"> 
      <% if @article.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@article.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @article.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
     
    <div class="form-group">
      Last Upddate: <%= @article.updated_at.strftime("%A, %B %d, %Y %l:%M %p") %>
    </div>

    <div class="form-group">
      <%= f.label :title %><br>
      <%= f.text_field :title, class: "form-control" %>
    </div>
   
    <div class="form-group">
      <%= f.label :text %><br>
      <%= f.text_area :text, class: "form-control", rows: "12" %>
    </div>
   
    <div class="form-group">
      <%= f.submit("Save changes", class: "btn btn-primary") %>
    </div>
     
  <% end %>
</form>

app/views/articles/edit.html.erb
<div class="container" id="show-container">
  <div class="col-sm-12">
    <h4 class="row text-xs-center">
      Edit
    </h4>
 
    <%= render 'form' %>
 
    <%= link_to 'Article List', articles_path %>
  </div>
</div>

app/views/articles/index.html.erb
<h1>Listing articles</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'New article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Article List', articles_path %>

app/views/articles/show.html.erb
<div class="container" id="show-container">
  <div class="col-sm-12">
    <h4 class="row text-xs-center">
      <%= @article.title %>
    </h4>
   
    <p class="row">
      <%= @article.text %>
    </p>

    <div class="row">
      <%= link_to 'Home Page', root_path %> |
      <%= link_to 'Articles', articles_path %> |
      <%= link_to 'Edit', edit_article_path(@article) %> |
      <%= link_to 'Destroy', article_path(@article), method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
   
    <div class="card" style="margin-top: 1em">
      <div class="card-header">
        <h5>Add a comment:</h5>
      </div>

      <div class="card-block">
        <%= render 'comments/form' %>
      </div>
    </div>
   
    <div class="card"> 
      <div class="card-header">
        <h5>Comments</h5>
      </div>
      
      <div class="card-block">
        <%= render @article.comments %>
      </div>
    </div>
  </div>

</div><!-- close container -->
 

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' },
               class: "btn btn-danger" %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit class: "btn btn-primary"%>
  </p>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-dark" >
  <div class="container-fluid">
    <div class="nav navbar-nav">  
      <%= link_to("Jeffrey Apollo", root_path, class: "navbar-brand", id: "nav-brand-style") %>   
      <%= link_to("Articles", articles_path, class: "nav-item nav-link") %>
      <%= link_to("Projects", "#", class: "nav-item nav-link") %>
      <%= link_to("About", "#", class: "nav-item nav-link") %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>Jeffrey Apollo</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/css/bootstrap.min.css" integrity="2hfp1SzUoho7/TsGGGDaFdsuuDL0LX2hnUp6VkX3CUQ2K4K+xjboZdsXyp4oUHZj" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %> 
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    
    <%= yield %>
    

    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js" integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js" integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/js/bootstrap.min.js" integrity="VjEeINv9OSwtWFLAtmc4JCtEJXXBub00gtSnszmspDLCtC0I4z4nqz7rEFbIZLLU" crossorigin="anonymous"></script>
  </body>
</html>

app/views/welcome/index.html.erb
<div id="main-image">
  <h1>Jeffrey Apollo</h1>
  <h5>A beginers guide to creating web based applications.</h5>
</div>
 
<div class="container" id="index-container">  
  <div class="col-sm-8" id="articles-index">
    <div class="card">
      <div class="card-header">
        <h4>Recent Articles</h4>
        <%= link_to 'New article', new_article_path, class: "btn btn-primary btn-sm" %>
      </div>

      <% @articles.each do |article| %>
        <div class="card card-block" style="margin: 1em">
          <h5 class="card-title"><%= article.title %></h5>
          <p class="card-text"><%= article.text %></p>
          <div class="card-text">
            <%= link_to 'Show', article_path(article) %> |
            <%= link_to 'Edit', edit_article_path(article) %> |
            <%= link_to 'Destroy', article_path(article), method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
      <% end %>

    </div>
  </div>

  <div class="col-sm-4" id="articles-index">
    <div class="card">
      <div class="card-header">
        <h4>Current Projects</h4>
        <%= link_to 'New project', new_article_path, class: "btn btn-primary btn-sm" %>
      </div>

      <% @articles.each do |article| %>
        <div class="card card-block" style="margin: 1em">
          <h5 class="card-title"><%= article.title %></h5>
          <p class="card-text"><%= article.text %></p>

          <div class="card-text">
            <%= link_to 'Show', article_path(article) %> |
            <%= link_to 'Edit', edit_article_path(article) %> |
            <%= link_to 'Destroy', article_path(article), method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

</div>